export function downloadBlob(filename, content, type='application/json'){
  const blob = new Blob([content], {type}); const url = URL.createObjectURL(blob);
  const a = document.createElement('a'); a.href = url; a.download = filename; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url);
}
export function escapeHtml(s=''){ return String(s).replace(/[&<>'"]/g, c=>({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[c])); }
export function buildHtmlReport(state){
  const k = state.kpis;
  const rows = state.actions.slice(0,10).map(a=>`<tr><td>${escapeHtml(a.agent_name)}</td><td>${escapeHtml(a.title)}</td><td>${escapeHtml(a.status)}</td><td>${escapeHtml(a.expected_impact)}</td></tr>`).join('');
  const events = state.events.slice(0,12).map(e=>`<li><b>${escapeHtml(e.severity)}</b> · ${escapeHtml(e.source)} · ${escapeHtml(e.event)}</li>`).join('');
  return `<!doctype html><html><head><meta charset="utf-8"><title>AIonOS Hitachi GCC Evidence Report</title><style>body{font-family:Arial,sans-serif;margin:40px;color:#111}h1{font-size:34px} .kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.kpi{border:1px solid #ddd;border-left:7px solid #ed001b;border-radius:12px;padding:16px}.kpi b{display:block;font-size:28px;margin-top:8px}table{width:100%;border-collapse:collapse;margin-top:20px}td,th{padding:10px;border-bottom:1px solid #eee;text-align:left}th{font-size:12px;text-transform:uppercase;color:#666}.box{background:#f6f7f9;border-radius:16px;padding:18px;margin:20px 0}</style></head><body><p>CONFIDENTIAL DEMO EVIDENCE PACK</p><h1>AIonOS Mission Control for Hitachi GCC Bengaluru</h1><p>Generated ${new Date().toLocaleString()} from a static browser-side JSON store. No backend was used.</p><div class="kpis"><div class="kpi">GCC Health<b>${k.gccHealth}</b></div><div class="kpi">K8s Health<b>${k.k8sHealth}</b></div><div class="kpi">DR Score<b>${k.drScore}</b></div><div class="kpi">Savings Identified<b>₹${k.savings}M</b></div></div><div class="box"><h2>Recent Live Signals</h2><ul>${events}</ul></div><h2>Agent Recommendations + Approvals</h2><table><tr><th>Agent</th><th>Action</th><th>Status</th><th>Expected impact</th></tr>${rows}</table><p><small>Evidence is synthetic and intended for client POV demonstration. Replace data JSON with real telemetry adapters for production.</small></p></body></html>`;
}